# Generated by Django 4.2.16 on 2026-03-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='current_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
