# Generated by Django 4.2.16 on 2026-03-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_galleryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='living_separately',
            field=models.BooleanField(default=False),
        ),
    ]
