# Generated by Django 4.2.16 on 2026-03-27 11:43

from django.db import migrations, models
import django.db.models.deletion
import tree.models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_person_living_separately'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_photos', to='tree.event'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=models.ImageField(upload_to=tree.models.gallery_upload_to),
        ),
    ]
