# Generated by Django 4.2.16 on 2026-04-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0009_sitead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitead',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
