# Generated by Django 4.2.16 on 2026-04-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0010_alter_sitead_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitead',
            name='display_type',
            field=models.CharField(choices=[('popup', 'Popup'), ('side', 'Side Ad'), ('section', 'Home Section')], default='popup', max_length=20),
        ),
        migrations.AddField(
            model_name='sitead',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelOptions(
            name='sitead',
            options={'ordering': ['-priority', '-created_at', '-id']},
        ),
    ]
