# Generated by Django 4.2.16 on 2026-04-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0011_sitead_display_type_sitead_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStreamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Live Stream', max_length=200)),
                ('youtube_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Live Stream Settings',
                'verbose_name_plural': 'Live Stream Settings',
            },
        ),
    ]
