# Generated by Django 4.2.16 on 2026-04-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0014_membercategory_membergroup_whatsappbroadcast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='public-site', max_length=50, unique=True)),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Visit Counter',
                'verbose_name_plural': 'Site Visit Counter',
            },
        ),
    ]
