from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('family/', views.family_page, name='family_page'),
    path('family/<int:guardian_pk>/', views.family_detail, name='family_detail'),
    path('events/', views.events, name='events'),
    path('events/<int:pk>/', views.event_detail, name='event_detail'),
    path('gallery/', views.gallery, name='gallery'),
    path('contact/', views.contact, name='contact'),
    path('admin-login/', views.admin_login, name='admin_login'),
    path('logout/', views.admin_logout, name='admin_logout'),
    path('admin-panel/', views.admin_panel, name='admin_panel'),
    path('admin-panel/members/', views.admin_members, name='admin_members'),
    path('admin-panel/member-users/', views.admin_member_users, name='admin_member_users'),
    path('admin-panel/members/add/', views.admin_member_add, name='admin_member_add'),
    path('admin-panel/members/<int:pk>/edit/', views.admin_member_edit, name='admin_member_edit'),
    path('admin-panel/members/<int:pk>/delete/', views.admin_member_delete, name='admin_member_delete'),
    path('admin-panel/events/', views.admin_events, name='admin_events'),
    path('admin-panel/events/add/', views.admin_event_add, name='admin_event_add'),
    path('admin-panel/events/<int:pk>/edit/', views.admin_event_edit, name='admin_event_edit'),
    path('admin-panel/events/<int:pk>/delete/', views.admin_event_delete, name='admin_event_delete'),
    path('admin-panel/ads/', views.admin_ads, name='admin_ads'),
    path('admin-panel/ads/add/', views.admin_ad_add, name='admin_ad_add'),
    path('admin-panel/ads/<int:pk>/edit/', views.admin_ad_edit, name='admin_ad_edit'),
    path('admin-panel/ads/<int:pk>/delete/', views.admin_ad_delete, name='admin_ad_delete'),
    path('admin-panel/gallery/', views.admin_gallery, name='admin_gallery'),
    path('admin-panel/gallery/add/', views.admin_gallery_add, name='admin_gallery_add'),
    path('admin-panel/gallery/<int:pk>/edit/', views.admin_gallery_edit, name='admin_gallery_edit'),
    path('admin-panel/gallery/<int:pk>/delete/', views.admin_gallery_delete, name='admin_gallery_delete'),
    path('tree/', views.tree_view, name='tree'),
    path('tree/data/', views.tree_data, name='tree_data'),
    path('people/', views.people_list, name='people_list'),
    path('people/add/', views.person_add, name='person_add'),
    path('people/<int:pk>/', views.person_detail, name='person_detail'),
    path('people/<int:pk>/edit/', views.person_edit, name='person_edit'),
    path('people/<int:pk>/delete/', views.person_delete, name='person_delete'),
]
